version: "3.8"

services:
  # ML Engine Service
  ml-engine:
    build:
      context: ./services/ml-engine
      dockerfile: Dockerfile
    container_name: messai-ml-engine
    ports:
      - "8001:8001"
    environment:
      - ML_SERVICE_NAME=messai-ml-engine
      - ML_VERSION=1.0.0
      - ML_DEBUG=false
      - ML_PORT=8001
      - ML_DATABASE_URL=${DATABASE_URL:-postgresql://messai:messai_dev_password@postgres:5432/messai_dev}
      - ML_REDIS_URL=redis://redis:6379
      - ML_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,https://messai.ai
      - ML_LOG_LEVEL=INFO
    volumes:
      - ./services/ml-engine:/app
      - ml-models:/app/models/saved
    depends_on:
      - postgres
      - redis
    networks:
      - messai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: messai-postgres
    environment:
      - POSTGRES_USER=messai
      - POSTGRES_PASSWORD=messai_dev_password
      - POSTGRES_DB=messai_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - messai-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: messai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - messai-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # MLflow for Model Registry (optional)
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: messai-mlflow
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=postgresql://messai:messai_dev_password@postgres:5432/messai_dev
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - mlflow-artifacts:/mlflow/artifacts
    networks:
      - messai-network
    depends_on:
      - postgres
    command: >
      mlflow server
      --backend-store-uri postgresql://messai:messai_dev_password@postgres:5432/messai_dev
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port 5000

volumes:
  postgres-data:
  redis-data:
  ml-models:
  mlflow-artifacts:

networks:
  messai-network:
    driver: bridge
