version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: messai-postgres
    environment:
      POSTGRES_USER: messai
      POSTGRES_PASSWORD: messai_dev_password
      POSTGRES_DB: messai_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U messai"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
